name: publish-latest

on:
    push:
        # should check on for release here instead of branch
        # we only want to publish the old packages on a v1.X.X tag
        tags:
            - "v1.*"

jobs:
    publish-latest:
        name: publish-latest
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
              with:
                  fetch-depth: 0
                  ref: ${{ github.ref }}

            # - name: cache
            #   uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf
            #   with:
            #       path: "**/node_modules"
            #       key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

            - name: node
              uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org/

            - name: install
              run: yarn install --frozen-lockfile

            - name: build
              run: yarn build:prod --filter="@adobe/magento*"

            - name: publish storefront sdk
              working-directory: ./packages/storefront-events-sdk
              run: yarn publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.ADOBE_BOT_NPM_TOKEN }}

            - name: publish storefront collector
              working-directory: ./packages/storefront-events-collector
              run: yarn publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.ADOBE_BOT_NPM_TOKEN }}
