name: pull-request

on:
    pull_request:
        branches:
            - main

jobs:
    pull_request:
        name: pull-request
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14.x, 16.x]
        steps:
            - name: checkout
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
              with:
                  fetch-depth: 0
                  ref: ${{ github.ref }}

            - name: cache
              uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

            - name: node ${{ matrix.node-version }}
              uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e
              with:
                  node-version: ${{ matrix.node-version }}
            - name: install dependencies
              run: yarn install --frozen-lockfile
            - run: yarn build
            - run: yarn lint
            - run: yarn test
